import ollama  
# library used to communicate with local LLM models via Ollama

import re  
# regular expression library used to extract code blocks from text

from config import LLM_MODEL  
# imports model name (example: phi3, tinyllama) from config file


def extract_code(text):
    # function used to extract only the code part from LLM response
    # text → response generated by LLM


    code_blocks = re.findall(r"```.*?\n(.*?)```", text, re.DOTALL)
    # searches for code blocks inside triple backticks ``` ```
    # regex explanation:
    # ```.*?\n  → matches starting markdown code block
    # (.*?)     → captures code content
    # ```       → matches closing markdown block
    # re.DOTALL → allows newline characters inside search


    if code_blocks:
        # checks if any code block is found

        return code_blocks[0].strip()
        # returns first detected code block
        # strip() removes extra spaces or new lines


    return text.strip()
    # if no markdown block found, return original text after removing spaces



def fix_code(code, error):
    # function that asks LLM to correct the generated code
    # code → previously generated code
    # error → error message produced during execution


    prompt = f"""
Fix this code.

Code:
{code}

Error:
{error}

Return only corrected code.
"""
    # prompt instructs LLM to fix syntax or logical errors
    # includes original code and error message
    # asks LLM to return only corrected code


    response = ollama.chat(
        # sends prompt to LLM via Ollama API

        model=LLM_MODEL,
        # specifies which model to use

        messages=[
            {
                "role": "user",
                "content": prompt
                # sends prompt as user message
            }
        ]
    )


    return extract_code(response["message"]["content"])
    # extracts only corrected code from LLM response
    # removes markdown formatting if present