def evaluate_code(query, code, error, context):
    # function used to evaluate performance of the LLM generated code
    # query → user input request
    # code → generated code from LLM
    # error → error message after execution
    # context → retrieved GitHub knowledge (RAG context)

    metrics = {}
    # dictionary used to store evaluation scores


    # 1. compilation success
    metrics["compilation_success"] = 1 if error == "" else 0
    # checks whether code executed without any error
    # if error is empty → score 1
    # if error exists → score 0


    # 2. code generated check
    metrics["code_generated"] = 1 if code.strip() != "" else 0
    # checks whether LLM generated any code
    # strip removes extra spaces/newlines
    # if code exists → score 1
    # if empty response → score 0


    # 3. relevance score
    query_words = query.lower().split()
    # converts query to lowercase and splits into words
    # example: "write python fibonacci"
    # becomes ["write","python","fibonacci"]

    match_count = 0
    # counter to track how many query words appear in generated code


    for word in query_words:
        # loops through each word in user query

        if word in code.lower():
            # checks if query word exists inside generated code text

            match_count += 1
            # increase counter when match is found


    if len(query_words) > 0:
        # ensures query contains words

        relevance_score = match_count / len(query_words)
        # calculates percentage of query words present in code

    else:

        relevance_score = 0
        # avoids division by zero if query is empty


    metrics["relevance_score"] = round(relevance_score, 2)
    # stores relevance score rounded to 2 decimal places


    # 4. hallucination check
    # identifies unrelated words generated by model
    # hallucination means model creates content not grounded in query/context

    combined_text = (query + " " + " ".join(context)).lower()
    # combines user query and GitHub context into single text
    # used as reference knowledge base


    code_words = code.lower().split()
    # splits generated code into individual words


    unrelated_words = 0
    # counter to track words not found in query/context


    for word in code_words:
        # iterate through words in generated code

        if word.isalpha() and word not in combined_text:
            # checks only alphabet words
            # identifies words not present in query or GitHub context

            unrelated_words += 1
            # increments hallucination counter


    hallucination_score = 1 - (unrelated_words / len(code_words)) if len(code_words) > 0 else 0
    # calculates hallucination score
    # fewer unrelated words → higher score
    # score range between 0 and 1


    metrics["hallucination_score"] = round(hallucination_score, 2)
    # stores hallucination score rounded to 2 decimal places


    # 5. github grounding check
    # verifies whether generated code is influenced by GitHub retrieved knowledge

    context_text = " ".join(context).lower()
    # merges GitHub context list into single string


    grounding_match = 0
    # counter for matching words between context and generated code


    for word in context_text.split():
        # iterate through each word in GitHub context

        if word in code.lower():
            # checks if context word appears in generated code

            grounding_match += 1
            # increment counter when match found


    github_grounding = 1 if grounding_match > 0 else 0
    # if at least one match exists → grounding considered successful


    metrics["github_grounding"] = github_grounding
    # store grounding score (1 or 0)


    # final accuracy score
    metrics["final_score"] = round(
        (
            metrics["compilation_success"]
            # ensures code runs successfully

            + metrics["code_generated"]
            # ensures code is generated

            + metrics["relevance_score"]
            # checks alignment with query

            + metrics["hallucination_score"]
            # penalizes hallucinated content

            + metrics["github_grounding"]
            # verifies GitHub knowledge usage
        ) / 5,
        # average of all metrics

        2
        # round result to 2 decimal places
    )


    return metrics
    # returns dictionary containing evaluation scores